CREATE DATABASE IF NOT EXISTS IJOB_IJOB_DB;

USE IJOB_IJOB_DB;

CREATE TABLE IF NOT EXISTS PLATFORM (
    PLATFORM_ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    SUPPORTED_FROM DATETIME NOT NULL,
    SUPPORTED_TO DATETIME,
    PRIMARY kEY (PLATFORM_ID)
)AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS JOB_STORE (
    JOB_STORE_ID BIGINT AUTO_INCREMENT,
    LINK VARCHAR(500) NOT NULL UNIQUE,
    DATA JSON NOT NULL,
    PLATFORM_ID BIGINT NOT NULL,
    UPDATED_AT DATETIME,
    PRIMARY KEY (JOB_STORE_ID),
    FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM(PLATFORM_ID)
)AUTO_INCREMENT=10000;


INSERT INTO PLATFORM (name, type, supported_from)
VALUES ('Careers24', 'source', '2021-07-04 18:39:36');
