export enum SchedulerConfType {
    CAREERS24JONDETAILSRESOLVER = 'CAREERS24JONDETAILSRESOLVER',
    CAREERS24JOBSTOREIMPORTER = 'CAREERS24JOBSTOREIMPORTER',
    DUPLICATECLEANER = 'DUPLICATECLEANER'
}